# Generated by Django 2.0.4 on 2018-05-16 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0002_auto_20180514_2301'),
    ]

    operations = [
        migrations.AddField(
            model_name='podcast',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='image_podcast', verbose_name='Photo'),
        ),
    ]
